name: build and deploy

on:
  push:
    branches:
      - master  # Make sure this is the correct branch
  pull_request:
    branches:
      - master

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.15.0'

      - name: Install Dependencies
        run: npm install
        working-directory: ./portfolio-v1/

      - name: Setup Environment Variables
        run: |
          sed -i "s/\${TMDB_KEY}/${{ secrets.TMDB_KEY }}/g" src/app/environment.ts


      - name: Build
        run: ng build --configuration=production
        working-directory: ./portfolio-v1/

      - name: List Build Output
        run: ls -al ./dist/angular-portfolio
        working-directory: ./portfolio-v1/

      - name: Deploy to S3
        run: aws s3 sync dist/ s3://jordan-portfolio-v1 --delete
        working-directory: ./portfolio-v1/
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'ap-southeast-2'
