name: build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.15.0' # or whatever version your project uses

      - name: Install Dependencies
        run: npm install

      - name: Setup Environment Variables
        run: |
          sed -i "s/\${TMDB_KEY}/${{ secrets.TMDB_KEY }}/g" src/app/environment.ts

      - name: Build
        run: npm run build
        env:
          TMDB_KEY: ${{ secrets.TMDB_KEY }} # Using the TMDB_KEY in the build process

      - name: List build output
        run: ls -l ./dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'ap-southeast-2' # or your AWS region

      - name: Change to Workspace Directory
        run: cd $GITHUB_WORKSPACE

      - name: Deploy to S3
        run: aws s3 sync dist/angular-portfolio s3://jordan-portfolio-v1 --delete
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'ap-southeast-2'


        

